### PR TITLE
Make the math tooltip appear below the line

### LINKED ISSUE #224: [FEATURE] Math Popup Preview below the line instead of above the line
# Description of the Problem
To be able to read the previous line that is above the line that I am currently editing with Latex, I either have to deactivate the Math Popup Preview or open a second tab with the same markdown file. This is very inconvenient if, for example, you are doing a proof and want/need to read the previous line.

# Description of the Solution
A simple solution would be to have the Math Popup Preview appear below the line that is currently being edited. I guess it is more likely that you will need what is above the line rather than what is below the line.

ps.:
Thanks for this great plugin, without it working with Latex in Obsidian would be a lot harder!

### PR DESCRIPTION
**Pull request by bdm-k**
Closes #224

### CODE REVIEW

**Comment by artisticat1** [comment]
Thank you for the PR. Can you make this a toggleable setting?

**Comment by bdm-k** [comment]
Sure. However, since this is my first time developing an Obsidian plugin, it may take some time.

**Comment by bdm-k** [comment]
https://github.com/artisticat1/obsidian-latex-suite/blob/27f3ac6c6575a8164c68de25de25cad60f37e4a7/src/settings/settings_tab.ts#L202-L203
`saveSettings` calls `refreshCMExtensions` internally, so line 202 is redundant. Is it all right if I correct this?

**Comment by artisticat1** [comment]
I see, thanks for catching that. Yes, feel free to correct it!

**Comment by artisticat1** [comment]
Thanks!

**Comment by Aradoexis** [comment]
Thank you so much! ❤

**Pull request merged**
