### PR TITLE
feat: allow snippet variables to be defined by the user

### LINKED ISSUE #63: [Feature Request] Can we define variables like $SYMBOL?
Thank you for building this awesome plugin. This plugin works pretty well and helps me to use latex.

I'm trying to build my own snippets, and the idea of $symbol variable can make snippet more elegant. Is it possible to define more variable and edit exist $symbol?

here's some example to show the importance of variable editing:

- `ll` is included in $symbol, which cause default snippet `lll` failed
- symbols can be set to different category, `times` need auto spacing, but  `leq` sometimes need auto subscript

### PR DESCRIPTION
**Pull request by Benjymack**
Closes #63.
Also allows #175, #160, #144 to be solved by users.

Creates a new option in settings where users can edit three of the existing snippet variables (`GREEK`, `SYMBOL` and `SHORT_SYMBOL`), or add new ones.

### CODE REVIEW

**Comment by Benjymack** [comment]
Unfortunately not, I haven't received a response from @artisticat1 yet.

**Comment by artisticat1** [comment]
Thank you for the PR! Some refactoring work was just completed in #146 -- would you mind rebasing on main? If you would prefer, I can also take care of it.

**Comment by Benjymack** [comment]
Sorry for the delay in making those changes.
I think I've resolved all of the conflicts, but let me know if any other changes should be made.

**Comment by artisticat1** [comment]
No worries - looks good to me! Thanks for your work.

**Pull request merged**
