### PR TITLE
Backspace functionality to delete both $ in empty inline math

### LINKED ISSUE #266: [FEATURE] Automatically delete pair of `$` signs when backspacing in inline math
When pressing backspace on a line with `$|$` where `|` represents the cursor, both signs should delete, not just the first one.

Making this issue but I'll hopefully create a PR to fix this.

### PR DESCRIPTION
**Pull request by bdm-k**
Closes #266 

If the implementation looks good, I'd like to proceed with the next steps, such as:

* making this feature toggleable
* organizing the code into a new file

### CODE REVIEW

**Comment by artisticat1** [comment]
Implementation looks fine to me!

I am not sure if this is necessary, but perhaps we should clear all tabstops when this effect is triggered.

**Comment by bdm-k** [comment]
Do you mean calling `removeAllTabstops`, which is defined in "tabstops_state_field.ts"?

**Comment by artisticat1** [comment]
Yeah, exactly.

**Comment by bdm-k** [comment]
Could you tell me specifically what other changes I should make?

**Comment by artisticat1** [comment]
I'm happy to merge after this is done:

> * making this feature toggleable
> * organizing the code into a new file

**Comment by bdm-k** [comment]
I'm having second thoughts. Isn't it a bit excessive to create a new file since there are only a few lines of code?

**Comment by artisticat1** [comment]
Actually, can we check whether `context.mode.inlineMath` is `true` instead of looking for `$` symbols? This would be more semantic as well as robust.

> I'm having second thoughts. Isn't it a bit excessive to create a new file since there are only a few lines of code?

That's true; it would be nice for consistency with the other functions/features though. I'll leave it up to you.

**Comment by bdm-k** [comment]
> Actually, can we check whether `context.mode.inlineMath` is `true` instead of looking for `$` symbols? This would be more semantic as well as robust.

In the case of `$|$`, `context.mode.inlineMath` will be `false`. So, we can't determine whether the cursor is inside an empty inline math or entirely outside of an inline math.

**Comment by artisticat1** [comment]
Oh, that sounds like unintended behaviour - I'll try to look into it.

**Comment by bdm-k** [comment]
When the text is `$$`, the syntax tree will be:
```
Document [1:0..1:2]
   └─ formatting_formatting-math_formatting-math-begin_keyword_math_math-block [1:0..1:2]: "$$"
```

On the other hand, when the text is `$x$`, the syntax tree will be:
```
Document [1:0..1:3]
   ├─ formatting_formatting-math_formatting-math-begin_keyword_math [1:0..1:1]: "$"
   ├─ math_variable-2 [1:1..1:2]: "x"
   └─ formatting_formatting-math_formatting-math-end_keyword_math_math- [1:2..1:3]: "$"
```

In the first case, no node contains "math-end" in its name, so `context.mode.inlineMath` will be `false`. Therefore, we must directly look for `$` symbols.

**Comment by artisticat1** [comment]
Okay, I'll go ahead and merge this then. Thank you!

**Pull request merged**
